### PR TITLE
Update addon API, split addon helper and loader and merge upstream

### PR DESCRIPTION
**Pull request by fwcd**
This PR...

* merges the two `addon_helper.py` versions
* gitignores the `addon` folder, thereby making it easier to locally use addons
* passes the to-be-rendered scene classes to each addon
* instantiates addons classes instead of referencing them directly (breaking API change!)
* splits the addon-handling code into two separate modules:
    * an addon loader responsible for loading and invoking addons
    * an addon helper exposing functionality and information (e.g. movie paths) to addons
* merges the most recent version of `3b1b/master`

### CODE REVIEW

**Comment by fwcd** [comment]
Additionally, this PR now passes the to-be-rendered scene classes to each addon.

**Comment by yoshiask** [comment]
Fails with the following:
```sh
C:\Users\{user}\Documents\Manim Archive\fwcd-manim 1-11-2020>py -3 manim.py example_scenes.py OpeningManimExample -pl
Traceback (most recent call last):
  File "manim.py", line 5, in <module>
    manimlib.main()
  File "C:\Users\jjask\Documents\Manim Archive\fwcd-manim 1-11-2020\manimlib\__init__.py", line 13, in main
    manimlib.addon_loader.read_addons(True)
  File "C:\Users\jjask\Documents\Manim Archive\fwcd-manim 1-11-2020\manimlib\addon_loader.py", line 35, in read_addons
    addons.append(addon.Addon())
AttributeError: module 'C:.Users.jjask.Documents.Manim Archive.fwcd-manim 1-11-2020.manimlib....addons.pptx_export.addon' has no attribute 'Addon'
```

The issue is with this change:
```py
# Read each Python file in the addons directory
for filename in glob.glob(os.path.join(manimlib.constants.ADDON_DIR, "*", "*.py")):
    # Open the file and add the module to addons[]
    addon = import_addon(filename)
    addons.append(addon.Addon())
```

What is `addon.Addon()` meant to refer to?

**Comment by fwcd** [comment]
I have renamed `Main` to `Addon`, since the latter is a more descriptive name IMO.

See the PR in `manim-pptx` for an application of these changes.

**Comment by yoshiask** [comment]
I just checked `addon.py` in `manim-pptx`, and the class name is still `Main`. After fixing that in the addon, I get this error:
```sh
Traceback (most recent call last):
  File "manim.py", line 5, in <module>
    manimlib.main()
  File "C:\Users\jjask\Documents\Manim Archive\fwcd-manim 1-11-2020\manimlib\__init__.py", line 13, in main
    manimlib.addon_loader.read_addons(True)
  File "C:\Users\jjask\Documents\Manim Archive\fwcd-manim 1-11-2020\manimlib\addon_loader.py", line 41, in read_addons
    if addon.loaded():
TypeError: loaded() takes 0 positional arguments but 1 was given
```

I suspect there's something wrong here:
```py
# Open the file and add the module to addons[]
addon = import_addon(filename)
addons.append(addon.Addon())
```

**Comment by fwcd** [comment]
Are you sure you are running https://github.com/yoshiask/manim-pptx/pull/3?

**Comment by yoshiask** [comment]
Aha, that would do it. Merging now

**Pull request merged**
